### ISSUE TITLE
Error in Internet Explorer 11: Object.defineProperty argument is not an Object

### ISSUE THREAD

**Issue by AstralStorm** [ungap/url-search-params#14]
I've tried to use this polyfill, version from master, and got the following error in IE 11 in standards mode:
```javascript
SCRIPT5007: Object.defineProperty: argument is not an Object
url-search-params.min.js (86,13)
```

**Comment by AstralStorm** [comment]
Never mind, there was a missing new keyword.

**Comment by WebReflection** [comment]
it happens, but usually 100% code coverage helps understanding the library actually works for real ;-)

glad you solved 👍
