### ISSUE TITLE
ExecJS::ProgramError: TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by joshunger** [ungap/url-search-params#15]
When I use this on SSR using ExecJS I'm getting the following error -

```
ExecJS::ProgramError: TypeError: Object.defineProperty called on non-object
```

I don't have the stack.

Any ideas?

Thanks.

**Comment by WebReflection** [comment]
SSR has it native so either use an importmap or don't use this polyfill?

**Comment by joshunger** [comment]
Let me check with ExecJS 🤔
