### ISSUE TITLE
Correct webpack syntax for URLSearchParams support to IE11 ?

### ISSUE THREAD

**Issue by corford** [ungap/url-search-params#3]
I'm using webpack and trying to polyfill `URLSearchParams` support for IE11 but can't seem to get it to work.

Is this not the right way to do it?
```javascript
plugins: [
    new webpack.ProvidePlugin({
      'URLSearchParams': '@ungap/url-search-params'
    })
]
```

If I do the above and then test for the polyfill via IE11's dev console:
```javascript
var paramsString = "q=URLUtils.searchParams&topic=api";
var searchParams = new URLSearchParams(paramsString);
```

I get `'URLSearchParams' is undefined`

**Comment by WebReflection** [comment]
You have to either import or require it as specified in the README.md

**Comment by corford** [comment]
I thought that's what specifying it as a plugin did? i.e. webpack will import it during build time if it sees a call to URLSearchParams somewhere. https://webpack.js.org/plugins/provide-plugin/

**Comment by WebReflection** [comment]
The moment you call it somewhere is the moment you import/require it

**Comment by WebReflection** [comment]
P.S. just to clarify, this is a module like everything else you import/require as module. In Webpack, rollup, whatever, this is a regular module that provides USP, either native or polyfilled, without polluting the global context. If you need to use this as global patch don't use bundlers and just add it as script on top of your page. Everything said has been already tested and it works as expected.

**Comment by corford** [comment]
I am not actually using URLSearchParams  in my app code but a third party module I'm importing uses it. So I wanted to patch the global context but do it within webpack rather than adding it as a standalone script.

I guess I could set the polyfill as the first entry point and then my app after it.

**Comment by WebReflection** [comment]
Then write `global.URLSearchParams = require(...this module...) In your code and call it a day

**Comment by corford** [comment]
`global` - of course! Webpack offers so many ways to skin a cat I sometimes get lost in the trees. That has solved it. Thanks.

**Comment by marcelotduarte** [comment]
This is a very well done polyfill, but I noticed that the author has a resistance. It was hard work figuring out how to get around this stubbornness, and now I've discovered this issue.
Maybe it would be good to put it in readme, so I put it here as an aid to others using webpack:

``
import "imports-loader?this=>window!@ungap/url-search-params/index.js";
``

**Comment by WebReflection** [comment]
> I noticed that the author has a resistance

in doing what, exactly?

> Maybe it would be good to put it in readme

happy to review a PR
