### ISSUE TITLE
IE11 - How to use the API `URLSearchParams.prototype.keys()` correctly?

### ISSUE THREAD

**Issue by htbkoo** [ungap/url-search-params#4]
Hi, thanks for creating this polyfill library. :+1: 

However I had encountered some issues when using it in IE 11.

### Description ###

After polyfilling with this library, the creation of `URLSearchParams` can run successfully without `TypeError`.
However it is not clear how to use [`URLSearchParams.prototype.keys`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/keys) correctly and building array from the iterator always returns empty array.

### Steps to Reproduce ###

1. Import / require this library as dependency
2. Install `array-from` as well as IE 11 does not support `Array.from`
3. Run the following code (after bundling with `webpack`)
```
var URLSearchParams = require('@ungap/url-search-params');
var arrayFrom = require("array-from");

var params = new URLSearchParams("key=value");

var asString = params.toString();
var asArray = arrayFrom(params.keys());

console.log(`asString: ${asString}`);
console.log(`asArray: ${JSON.stringify(asArray)}`);
```

**Expected behaviour:**
The following are printed to console (e.g. in both Chrome and node.js):

`
asString: key=value
asArray: ["key"]
`

**Actual behaviour:**
The following are printed to console in IE 11:

`
asString: key=value
asArray: []
`

As you can see, the array is always empty.
Also it does not appear that the iterator from `params.keys()` is iterable either.

**Comment by WebReflection** [comment]
you are filing a bug in the wrong place:
https://github.com/studio-b12/array-from/blob/master/polyfill.js#L18-L34

this poly implements the iterator protocol through `next()` ... use a different Array.from polyfill or ask them to check for `next` callback instead

**Comment by htbkoo** [comment]
Thanks for the prompt response 👍 
And apologies for filing the bug mistakenly here.

**Comment by WebReflection** [comment]
well, you gave me a hint that an `Array.from` poly here in `@ungap` would be welcome
