### ISSUE TITLE
Is this not the correct way to use URLSearchParams in IE11?

### ISSUE THREAD

**Issue by ramonjsantiago** [ungap/url-search-params#5]
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <script type="text/javascript">
            if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
                document.write('<script src="https://unpkg.com/@ungap/url-search-params"><\/script>');
            }
        </script>
    </head>
    <body onload="something()">
        <script>
            var something= function () {
...
                    var urlSearchParams = new URLSearchParams(window.location.search);
...
            };
        </script>
    </body>
</html>

In the IE11 console I get
SCRIPT1028: Expected identifier, string or number
url-search-params (34,7)

which seems to be this line;

      delete: function (key) {

**Comment by WebReflection** [comment]
```html
<script>
if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
  window.URLSearchParams = void 0;
  document.write('<script src="https://unpkg.com/@ungap/url-search-params"><\x2fscript>');
}
</script>
```
