### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by eddiemonge** [ungap/url-search-params#6]
It would be nice if type definitions were included

**Comment by WebReflection** [comment]
PR welcome, 'cause I don't TypeScript so I don't even know what to do, thanks

**Comment by nikolay-borzov** [comment]
You don't need type definitions for `URLSearchParams` because TypeScript has built-in ones inside [lib.dom.iterable.d.ts](https://github.com/microsoft/TypeScript/blob/3d09010dc8916446f3e7a00df7845bc982ae721f/lib/lib.dom.iterable.d.ts#L225)

**Comment by WebReflection** [comment]
thanks @nikolay-borzov for clarification

**Comment by eddiemonge** [comment]
Yet VSCode doesn't recognize this module as `URLSearchParams` since it is imported. Therefore I think this still needs the type definitions, probably a simple extends would work

**Comment by nikolay-borzov** [comment]
I didn't notice you have to use default import. I thought a polyfill is supposed to be imported as a side effect
```
import '@ungap/url-search-params'
```

**Comment by WebReflection** [comment]
Then my initial answer remains: please file a PR, thanks

**Comment by eddiemonge** [comment]
Can this be reopened then?
