### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by Floles** [ungap/url-search-params#9]
Hi,

Since this morning, I tried to compile with webpack but in my CI logs (on gitlab), I have this issue :

`error An unexpected error occurred: "https://registry.yarnpkg.com/@ungap/url-search-params/-/url-search-params-0.1.2.tgz: Request failed \"503 Service Unavailable\"".`

Please let me know about it !
Thank you

**Comment by Floles** [comment]
The service is back so I close this issue !!

**Comment by WebReflection** [comment]
just to clarify, if `yarn` or `npm` have issues, you should **not** file bugs to every module you're trying to bundle, not even one :sweat_smile:
